/**
 * Made-up days for the brief writer's corpus. Each one is the input the
 * worker's gatherBrief would hand the writer, written short; build.mjs turns
 * it into that shape with the worker's own code (shape of the day, clashes,
 * behind this week, the offer rule).
 *
 * Real days (built from someone's own data) go in real/*.json in the same
 * format. That folder is gitignored; never commit one.
 *
 * Times are local "HH:MM". A habit is { title, daily: true } or
 * { title, target, done } for a weekly target, or { title, breaking: true }.
 */

const PRIYA = { first_name: 'Priya', pronouns: 'she/her' };
const ALEX = { first_name: 'Alex', pronouns: null };
const SAM = { first_name: 'Sam', pronouns: 'they/them' };

export const SCENARIOS = [
  {
    id: 'busy-morning',
    title: 'Busy morning, clear afternoon',
    look: 'Names the one or two meetings that matter (from the claims), mentions the 9:30 clash, says the afternoon is clear, offers to plan the afternoon.',
    today: '2026-10-01',
    at: '07:40',
    person: PRIYA,
    meetings: [
      ['08:00', '08:30', 'NA standup'],
      ['08:30', '09:15', 'Programmatic weekly'],
      ['09:30', '10:00', 'Fee planning'],
      ['09:30', '10:00', 'Paid social check-in'],
      ['10:30', '11:30', 'QBR prep with Dana'],
      ['11:30', '12:00', 'Media plan review'],
      ['12:00', '12:30', '1:1 with Marcus'],
    ],
    todos: ['Send QBR deck to Dana', 'Book flights for Denver', 'Reply to the agency brief'],
    habits: [
      { title: 'Stretch', daily: true },
      { title: 'Strength', target: 3, done: 1 },
      { title: 'Read 20 pages', target: 5, done: 0 },
    ],
    claims: [
      { title: 'QBR prep with Dana', why: 'The QBR is on Monday and this is the last prep session' },
      { title: 'Send QBR deck to Dana', why: 'Dana needs it before the prep at 10:30' },
    ],
    anchors: [{ date: '2026-10-05', short_label: 'QBR', label: 'Priya presents the QBR on Monday 5 October.' }],
    overdue: 0,
    unsorted: 2,
  },
  {
    id: 'light-day',
    title: 'Light day with a reach',
    look: 'Calm. Mentions the one meeting, and the reach (car service) only with its reason. Offers to plan the day.',
    today: '2026-10-06',
    at: '08:10',
    person: ALEX,
    meetings: [['10:00', '10:30', 'Design crit']],
    todos: ['Renew the parking permit', 'Return the library books'],
    habits: [{ title: 'Walk', daily: true }],
    claims: [{ title: 'Renew the parking permit', why: 'The permit runs out on Thursday' }],
    reach: {
      title: 'Book the car service',
      why: 'Alex said the car is overdue for a service and the garage takes weekday bookings',
      facts: ['Alex said the car is a few months overdue for its service.'],
    },
    anchors: [],
    overdue: 0,
    unsorted: 1,
  },
  {
    id: 'noon-open',
    title: 'Opened at noon',
    look: 'Only the rest of the day. The morning meetings are over and must not be described as coming up. Offers to plan the afternoon.',
    today: '2026-10-01',
    at: '12:20',
    person: PRIYA,
    meetings: [
      ['08:00', '08:30', 'NA standup'],
      ['09:00', '10:00', 'Fee planning'],
      ['11:00', '11:45', 'Paid social check-in'],
      ['15:00', '15:30', 'Client call with Northwind'],
    ],
    todos: ['Send QBR deck to Dana', 'Book flights for Denver'],
    habits: [{ title: 'Stretch', daily: true }],
    claims: [{ title: 'Client call with Northwind', why: 'They are deciding on the renewal this week' }],
    anchors: [],
    overdue: 0,
    unsorted: 0,
  },
  {
    id: 'evening-open',
    title: 'Opened in the evening',
    look: 'Evening wording, nothing about the day ahead as if it were morning. Offers to plan the evening.',
    today: '2026-10-01',
    at: '18:30',
    person: SAM,
    meetings: [
      ['09:00', '10:00', 'Team sync'],
      ['14:00', '15:00', 'Workshop'],
    ],
    todos: ['Call Mum', 'Pay the water bill'],
    habits: [
      { title: 'Journal', daily: true },
      { title: 'Run', target: 3, done: 0 },
    ],
    claims: [{ title: 'Pay the water bill', why: 'It is due today' }],
    anchors: [],
    overdue: 0,
    unsorted: 3,
  },
  {
    id: 'messy-backlog',
    title: 'Messy backlog with a question',
    look: 'Asks the question with the stored answers as buttons. Offers Sweep first, kindly; planning comes after. No shame about the backlog.',
    today: '2026-10-01',
    at: '08:05',
    person: ALEX,
    meetings: [['13:00', '14:00', 'Dentist']],
    todos: ['Submit the expense report'],
    habits: [{ title: 'Walk', daily: true }],
    claims: [{ title: 'Dentist', why: 'The only fixed thing today' }],
    anchors: [],
    overdue: 6,
    unsorted: 9,
    question: { question: 'Is your haircut this Friday or Saturday?', choices: ['Friday', 'Saturday'] },
  },
  {
    id: 'question-no-choices',
    title: 'A question with no stored answers',
    look: 'The writer adds two to four short answers for the question.',
    today: '2026-10-02',
    at: '07:55',
    person: PRIYA,
    meetings: [['09:00', '09:30', 'Standup']],
    todos: ['Order a birthday present for Leo'],
    habits: [],
    claims: [],
    anchors: [{ date: '2026-10-09', short_label: "Leo's birthday", label: "Leo's birthday is on 9 October." }],
    overdue: 0,
    unsorted: 0,
    question: { question: "Is Leo's party at your place or at the park?", choices: [] },
  },
  {
    id: 'return-week',
    title: 'Back after eight days away',
    look: 'Welcome once, warmly; time away is fine. No counts or hints of what was missed in the lines. No question (one is in the input and must be held back). Sweep offered gently with Catch me up; catch-up text uses the counts.',
    today: '2026-10-07',
    at: '08:30',
    person: SAM,
    meetings: [['11:00', '11:30', 'Team sync']],
    todos: ['Renew passport'],
    habits: [
      { title: 'Run', target: 3, done: 0 },
      { title: 'Journal', daily: true },
    ],
    claims: [],
    anchors: [],
    overdue: 12,
    unsorted: 14,
    ret: { days_away: 8, note: 'Good to see Sam back; time away is fine.' },
    question: { question: 'Did the move to the new flat happen?', choices: ['Yes', 'Not yet'] },
  },
  {
    id: 'weekend',
    title: 'Saturday with nothing booked',
    look: 'A weekend tone. The anniversary chip is on the card; the lines mention it only if today needs it. Offers to plan the day lightly.',
    today: '2026-10-03',
    at: '09:30',
    person: PRIYA,
    meetings: [],
    allDay: ['Farmers market'],
    todos: ['Pick up the dry cleaning'],
    habits: [
      { title: 'Yoga', target: 1, done: 0 },
      { title: 'Run', target: 1, done: 0 },
    ],
    claims: [],
    anchors: [{ date: '2026-10-13', short_label: 'Anniversary', label: 'Priya and Tom’s anniversary is on 13 October.' }],
    overdue: 0,
    unsorted: 0,
  },
  {
    id: 'anniversary-trip',
    title: 'Flying out on an anniversary trip, the anniversary itself later',
    look: 'Leads with flying to San Diego today and leaving at 12:30. Points out that timesheets at 4pm falls after they set off. Never says the anniversary is today (it is on 7 October). Any Sweep number is 6, the drops since the last Sweep.',
    today: '2026-10-02',
    at: '06:10',
    person: ALEX,
    meetings: [
      ['08:00', '08:30', 'Team huddle'],
      ['16:00', '16:30', 'Timesheets'],
    ],
    todos: ['Find a present and give it to Sam', 'Send out the partner deck', 'Submit to the app store'],
    habits: [{ title: 'Pushups', target: 2, done: 0 }],
    claims: [],
    anchors: [
      { date: '2026-10-07', short_label: 'Anniversary', label: 'Alex and Sam’s anniversary is on 7 October.' },
    ],
    dayShape: 'Anniversary trip to San Diego with Sam from 2 to 4 October, flying down this afternoon.',
    overdue: 0,
    unsorted: 6,
    // ten cards in the evening Sweep; the six with no day were dropped after
    // last night's Sweep at 8:41pm
    sweepAll: 10,
    newSince: 6,
    lastSweepAt: '2026-10-02T03:41:00Z',
    travel: ['Flying to San Diego', '12:30'],
    blocks: [['12:30', 'Leave for the airport', true]],
    forbid: ['happy anniversary', 'anniversary today', 'your anniversary is today'],
  },
  {
    id: 'travel-day',
    title: 'Travel day',
    look: 'Builds the day around the flight. Does not suggest planning into the flight time.',
    today: '2026-10-04',
    at: '07:15',
    person: ALEX,
    meetings: [
      ['10:00', '10:30', 'Hotel checkout'],
      ['11:05', '12:40', 'Flight AS 1234 San Diego to San Francisco'],
    ],
    todos: ['Pack the laptop charger'],
    habits: [{ title: 'Walk', daily: true }],
    claims: [{ title: 'Flight AS 1234 San Diego to San Francisco', why: 'Leave for the airport by 10:15' }],
    anchors: [],
    overdue: 0,
    unsorted: 0,
    travel: ['Flying home to San Francisco', null],
    travelMeetings: [1],
  },
  {
    id: 'no-calendar',
    title: 'No calendar connected',
    look: 'Does not claim the day is empty of meetings as a fact about their life; talks about the todos and habits. Offers to plan the day.',
    today: '2026-10-07',
    at: '08:00',
    person: SAM,
    meetings: [],
    todos: ['Write the grant report', 'Email the landlord', 'Buy oat milk', 'Book the vet'],
    habits: [
      { title: 'Meditate', daily: true },
      { title: 'Swim', target: 2, done: 0 },
    ],
    claims: [{ title: 'Write the grant report', why: 'It is due on Friday' }],
    anchors: [],
    overdue: 0,
    unsorted: 0,
  },
  {
    id: 'new-user',
    title: 'Second day of training',
    look: 'Thin data. Short, warm, no invented context. Offers to plan the day.',
    today: '2026-10-02',
    at: '08:30',
    person: { first_name: 'Jo', pronouns: null },
    gremlyAge: 1,
    meetings: [],
    todos: ['Buy a new kettle'],
    habits: [],
    claims: [],
    anchors: [],
    overdue: 0,
    unsorted: 1,
  },
  {
    id: 'nothing-to-offer',
    title: 'Late evening, nothing left',
    look: 'No offer: one warm sign-off. Nothing invented.',
    today: '2026-10-01',
    at: '21:30',
    person: PRIYA,
    meetings: [['09:00', '10:00', 'Team sync']],
    todos: [],
    habits: [],
    claims: [],
    anchors: [],
    overdue: 0,
    unsorted: 0,
  },
  {
    id: 'after-yesterday',
    title: "Reads yesterday's reaction",
    look: 'Uses what happened yesterday lightly, if at all, and never as a judgement.',
    today: '2026-10-02',
    at: '07:45',
    person: PRIYA,
    meetings: [['09:00', '09:30', 'Standup']],
    todos: ['Send QBR deck to Dana'],
    habits: [{ title: 'Strength', target: 3, done: 1 }],
    claims: [{ title: 'Send QBR deck to Dana', why: 'It slipped yesterday and the QBR is on Monday' }],
    anchors: [{ date: '2026-10-05', short_label: 'QBR', label: 'Priya presents the QBR on Monday 5 October.' }],
    overdue: 0,
    unsorted: 0,
    reaction:
      "YESTERDAY'S BRIEF (Thursday): they opened it; they tapped \"Plan my afternoon\"; they locked in a plan of 3 items and took out Strength on the way.",
  },
];
