/**
 * Log Subtype Tag Mapping
 *
 * Automatically adds and marks sticky the appropriate tag for log subtypes.
 * Ensures that logs always have their subtype tag (e.g., #idea, #journal)
 * even if AI doesn't generate it.
 *
 * Also filters out low-quality tags and legacy internal markers.
 */

import { filterAndNormalizeTags } from '../tags/normalize';

export interface TagsMeta {
  sticky: string[];
  tombstones: string[];
}

const LOG_SUBTYPE_TAGS: Record<string, string> = {
  idea: '#idea',
  journal: '#journal',
  reflection: '#reflection',
  insight: '#insight',
  decision: '#decision',
  list: '#list',
};

/**
 * Merge AI tags with subtype-specific sticky tag for logs
 *
 * Filters out:
 * - Internal markers (e.g., *idea, *journal) - legacy system tags
 * - Old-style hash tags (e.g., #been, #bit, #down) - we re-add subtype tag explicitly
 * - Low-quality tags (via isGoodTag)
 *
 * Keeps:
 * - High-quality AI tags (overwhelmed, self-care, mindfulness, etc.)
 * - Subtype tag (#idea, #journal, etc.) - marked as sticky
 *
 * @param aiTags - Tags generated by AI (from Cortex)
 * @param existingTags - Tags already on the entity (may include system tags)
 * @param subtype - Log subtype (idea, journal, etc.)
 * @param labels - Entity labels (to detect if it's a log)
 * @param tagsMeta - Existing tags metadata with sticky/tombstones
 * @returns Merged tags array and updated tags_meta
 */
export function mergeLogSubtypeTag(
  aiTags: string[] | null | undefined,
  existingTags: string[] | null | undefined,
  subtype: string | null | undefined,
  labels: string[] | null | undefined,
  tagsMeta: TagsMeta | null | undefined,
): { tags: string[]; tags_meta: TagsMeta } {
  const subtypeTag = subtype && LOG_SUBTYPE_TAGS[subtype] ? LOG_SUBTYPE_TAGS[subtype] : null;

  const isLog =
    (labels ?? []).includes('log') || (subtype && LOG_SUBTYPE_TAGS[subtype] !== undefined);

  const merged = [...(aiTags ?? []), ...(existingTags ?? [])];

  // Drop internal markers like *idea / *journal completely
  const withoutInternalMarkers = merged.filter((raw) => raw && !raw.startsWith('*'));

  // Filter through unified junk filter (removes #been, #bit, #actually, short tags, etc.)
  const cleaned = filterAndNormalizeTags(withoutInternalMarkers);
  const seen = new Set<string>(cleaned.map((t) => t.toLowerCase()));

  // Always add the subtype tag (e.g. #idea / #journal) for logs
  const nextTagsMeta: TagsMeta = {
    sticky: [...(tagsMeta?.sticky ?? [])],
    tombstones: [...(tagsMeta?.tombstones ?? [])],
  };

  if (isLog && subtypeTag) {
    const key = subtypeTag.toLowerCase();
    if (!seen.has(key)) {
      cleaned.push(subtypeTag);
      seen.add(key);
    }
    if (!nextTagsMeta.sticky.includes(subtypeTag)) {
      nextTagsMeta.sticky.push(subtypeTag);
    }
  }

  return { tags: cleaned, tags_meta: nextTagsMeta };
}
