/**
 * Log Subtype Tag Mapping
 *
 * Automatically adds and marks sticky the appropriate tag for log subtypes.
 * Ensures that logs always have their subtype tag (e.g., #idea, #journal)
 * even if AI doesn't generate it.
 *
 * Also filters out low-quality tags and legacy internal markers.
 */

import { filterAndNormalizeTags } from '../tags/normalize';
import { applyTagQualityFilter } from '../tags/quality';
import { applyThemeTags } from '../tags/themes';

export interface TagsMeta {
  sticky: string[];
  tombstones: string[];
}

const LOG_SUBTYPE_TAGS: Record<string, string | null> = {
  idea: '#idea',
  journal: '#journal',
  reflection: '#reflection',
  insight: '#insight',
  decision: '#decision',
  list: '#list',
  // everything_else intentionally has no visible tag - the subtype metadata is sufficient
  everything_else: null,
};

/**
 * Merge AI tags with subtype-specific sticky tag for logs
 *
 * CP-TAG-4: Defensive tag merging sanity
 * - Filters both AI and existing tags through applyTagQualityFilter (removes junk)
 * - Strips internal markers (* prefix)
 * - Normalizes through filterAndNormalizeTags (removes stop words, validates format)
 * - Adds subtype tag (#journal, #idea, etc.) as sticky metadata
 * - If all meaningful tags filter out, result may be [#journal] only - this is VALID
 *
 * Filters out:
 * - Internal markers (e.g., *idea, *journal) - legacy system tags
 * - Old-style hash tags (e.g., #been, #bit, #down) - we re-add subtype tag explicitly
 * - Low-quality tags (via applyTagQualityFilter)
 * - CP-TAG-1: Contraction fragments (#don, #idk, #soon)
 *
 * Keeps:
 * - High-quality AI tags (overwhelmed, self-care, mindfulness, etc.)
 * - Subtype tag (#idea, #journal, etc.) - marked as sticky
 * - CP-TAG-3: @ tags (mentions) preserved as first-class citizens
 *
 * Phase 4B: Applies additive theme tags (e.g., #money for bills/rent)
 *
 * @param aiTags - Tags generated by AI (from Cortex)
 * @param existingTags - Tags already on the entity (may include system tags)
 * @param subtype - Log subtype (idea, journal, etc.)
 * @param labels - Entity labels (to detect if it's a log)
 * @param tagsMeta - Existing tags metadata with sticky/tombstones
 * @param text - Optional text content for theme tag detection (body/title/rawSentence)
 * @returns Merged tags array and updated tags_meta
 */
export function mergeLogSubtypeTag(
  aiTags: string[] | null | undefined,
  existingTags: string[] | null | undefined,
  subtype: string | null | undefined,
  labels: string[] | null | undefined,
  tagsMeta: TagsMeta | null | undefined,
  text?: string,
): { tags: string[]; tags_meta: TagsMeta } {
  const subtypeTag = subtype && LOG_SUBTYPE_TAGS[subtype] ? LOG_SUBTYPE_TAGS[subtype] : null;

  const isLog =
    (labels ?? []).includes('log') || (subtype && LOG_SUBTYPE_TAGS[subtype] !== undefined);

  // Apply quality filter to existing tags BEFORE merging
  // This drops junk tags like #has, #lately that may have been stored initially
  const cleanedExistingTags = applyTagQualityFilter(existingTags);
  const cleanedAiTags = applyTagQualityFilter(aiTags);

  const merged = [...cleanedAiTags, ...cleanedExistingTags];

  // Drop internal markers like *idea / *journal completely
  const withoutInternalMarkers = merged.filter((raw) => raw && !raw.startsWith('*'));

  // Filter through unified junk filter (removes #been, #bit, #actually, short tags, etc.)
  const cleaned = filterAndNormalizeTags(withoutInternalMarkers);

  // Phase 4B: Apply theme tags if text is provided (additive)
  const withThemes = text ? applyThemeTags(text, cleaned) : cleaned;

  const seen = new Set<string>(withThemes.map((t) => t.toLowerCase()));

  // Always add the subtype tag (e.g. #idea / #journal) for logs
  const nextTagsMeta: TagsMeta = {
    sticky: [...(tagsMeta?.sticky ?? [])],
    tombstones: [...(tagsMeta?.tombstones ?? [])],
  };

  if (isLog && subtypeTag) {
    const key = subtypeTag.toLowerCase();
    if (!seen.has(key)) {
      withThemes.push(subtypeTag);
      seen.add(key);
    }
    if (!nextTagsMeta.sticky.includes(subtypeTag)) {
      nextTagsMeta.sticky.push(subtypeTag);
    }
  }

  return { tags: withThemes, tags_meta: nextTagsMeta };
}
