// TAG_STOP_WORDS: Common filler words that should NOT become tags.
// NOTE: Keep meaningful nouns/activities (email, call, walk, run, read, write, clean, etc.)
// These can be both verbs AND nouns, so they make valid tags.
// Only filter pure action verbs that aren't also nouns (book=reserve, find, build, etc.)
export const TAG_STOP_WORDS = new Set<string>([
  // Articles and prepositions
  'a',
  'an',
  'and',
  'at',
  'for',
  'of',
  'on',
  'the',
  'to',
  'with',

  // Pronouns and demonstratives
  'anything',
  'everything',
  'nothing',
  'something',
  'stuff',
  'thing',
  'things',

  // Time words (keep as stop words - not meaningful as tags)
  'about',
  'after',
  'afternoon',
  'am',
  'before',
  'daily',
  'day',
  'days',
  'during',
  'each',
  'evening',
  'every',
  'hour',
  'hours',
  'later',
  'min',
  'mins',
  'minute',
  'minutes',
  'month',
  'monthly',
  'months',
  'morning',
  'next',
  'night',
  'pm',
  'sometime',
  'soon',
  'time',
  'times',
  'today',
  'tomorrow',
  'week',
  'weekly',
  'weeks',
  'year',
  'years',
  'yesterday',

  // Filler/conversational words
  'actually',
  'all',
  'almost',
  'awesome',
  'because',
  'been',
  'bit',
  'cant',
  'common',
  'cool',
  'doable',
  'doing',
  'don',
  'done',
  'dont',
  'down',
  'found',
  'fun',
  'get',
  'getting',
  'going',
  'gonna',
  'good',
  'got',
  'great',
  'here',
  'idk',
  'im',
  'ive',
  'just',
  'kinda',
  'made',
  'make',
  'maybe',
  'meant',
  'near',
  'need',
  'needs',
  'nice',
  'not',
  'probably',
  'put',
  'really',
  'seems',
  'some',
  'start',
  'stop',
  'sure',
  'take',
  'try',
  'up',
  'very',
  'wanna',
  'want',
  'wants',
  'went',

  // Pure action verbs (not also nouns) - filter when extracted as tags
  'book', // as in "book an appointment", not "a book" (use #reading instead)
  'find',
  'build',
  'ask',

  // Contraction fragments
  've',
  'll',
  're',
  'd',
]);
