/**
 * The day turn's replay suite: messages typed in today's thread, built on the
 * real 1 and 2 October mornings (with made-up names and items), and made-up
 * edge cases. Each says what the turn must and must not do.
 *
 * A scenario: today, at (HH:MM), text, question, history, items, meetings,
 * record ({ travel: [label, 'HH:MM' | null], blocks: [['HH:MM', title, travel]] }),
 * plan ({ status, items: [[id, 'HH:MM', minutes]] }), and expect:
 *   aboutDay        true or false
 *   changes         every one must be on the card: { kind (or kinds), id, at }
 *   forbid          kinds (or kind:id) that must not be on the card
 *   status          checklist statuses that must appear
 *   maxChanges      at most this many changes
 *   dueBefore       { id or title, before: YYYY-MM-DD }: what gets someone ready
 *                   for a later date is due before it, or Gremly asks (needs_answer)
 *   oneDate         a new todo has one date, unless the person named a deadline
 *   offersEvent     { title, day }: the event they mentioned is offered too (warn)
 *   mentions        words the reply should cover (warn)
 *   maxModelCalls   at most this many model calls for the message (warn)
 * A scenario may also carry tasks: Gremly's task list so far in the thread.
 */

const ALEX_ITEMS = [
  { id: 'mum', kind: 'todo', title: 'Call Mum', due_day: '2026-10-02', minutes: 20, note: 'in the plan' },
  { id: 'deck', kind: 'todo', title: 'Send the partner deck', due_day: '2026-10-03', minutes: 60, note: 'upcoming' },
  { id: 'present', kind: 'todo', title: 'Find a present for Sam', due_day: '2026-10-02', minutes: 45, note: 'in the plan' },
  { id: 'calendar', kind: 'todo', title: 'Set up the shared calendar', due_day: '2026-10-02', minutes: 20, note: 'due today' },
  { id: 'pushups', kind: 'habit', title: 'Pushups', minutes: 10, note: 'habit today' },
];


const SAT_ITEMS = [
  { id: 'taxes', kind: 'todo', title: 'Do taxes', due_day: '2026-10-03', minutes: 60, note: 'due today' },
  { id: 'flowers', kind: 'todo', title: 'Water the plants', due_day: '2026-10-04', minutes: 10, note: 'upcoming' },
  { id: 'deck', kind: 'todo', title: 'Send the partner deck', due_day: '2026-10-05', minutes: 60, note: 'upcoming' },
  { id: 'gift', kind: 'todo', title: 'Find a present for Sam', due_day: '2026-10-05', minutes: 45, note: 'upcoming' },
  { id: 'qbr', kind: 'todo', title: 'Schedule the QBR', due_day: '2026-10-08', minutes: 20, note: 'upcoming' },
  { id: 'vet', kind: 'todo', title: 'Book the vet for Bella', due_day: '2026-10-09', minutes: 15, note: 'upcoming' },
  { id: 'pushups', kind: 'habit', title: 'Pushups', minutes: 10, note: 'habit today' },
];

export const SCENARIOS = [
  {
    id: 'airport-and-call',
    title: '2 October: a call at 12 and leaving for the airport at 12:30',
    look: 'One card: Call Mum moves to 12:00 and a set time "leave for the airport" at 12:30 (travel). No claim that anything is done.',
    today: '2026-10-02',
    at: '09:04',
    text: 'I need to call my parents at 12 and then leave for the airport at 12:30',
    items: ALEX_ITEMS,
    meetings: [
      ['08:00', '08:30', 'Team huddle'],
      ['16:00', '16:30', 'Timesheets'],
    ],
    record: { travel: ['Flying to San Diego', null], blocks: [] },
    plan: {
      status: 'proposal',
      items: [
        ['present', '09:30', 45],
        ['mum', '11:50', 20],
      ],
    },
    expect: {
      aboutDay: true,
      changes: [
        { kinds: ['retime', 'plan_move'], id: 'mum', at: '12:00' },
        { kinds: ['add_block'], at: '12:30', travel: true },
      ],
      forbid: ['create_todo'],
      maxChanges: 3,
    },
  },
  {
    id: 'flying-today',
    title: '2 October (the other side): "we fly today" with no time yet',
    look: 'Asks when they set off or proposes nothing it cannot know; never moves or skips a habit it was not asked about.',
    today: '2026-10-02',
    at: '08:07',
    text: "we're flying to San Diego today, can you plan around that?",
    items: [
      { id: 'workout', kind: 'habit', title: 'Work out', minutes: 30, note: 'habit today' },
      { id: 'card', kind: 'todo', title: 'Buy an anniversary card', due_day: '2026-10-07', minutes: 15, note: 'upcoming' },
      { id: 'pack', kind: 'todo', title: 'Pack', due_day: '2026-10-02', minutes: 30, note: 'due today' },
    ],
    meetings: [],
    record: { travel: ['Flying to San Diego', null], blocks: [] },
    plan: null,
    expect: {
      aboutDay: true,
      forbid: ['skip_habit', 'move_day:workout', 'retime:workout', 'cancel'],
      status: ['needs_answer'],
      maxChanges: 1,
    },
  },
  {
    id: 'flying-at-three',
    title: 'Flying at 3, leaving at 1',
    look: 'A travel set time at 13:00; nothing moved that was not asked for.',
    today: '2026-10-02',
    at: '08:10',
    text: 'our flight is at 3, we leave the house at 1',
    items: [
      { id: 'workout', kind: 'habit', title: 'Work out', minutes: 30, note: 'habit today' },
      { id: 'pack', kind: 'todo', title: 'Pack', due_day: '2026-10-02', minutes: 30, note: 'due today' },
    ],
    meetings: [],
    record: { travel: ['Flying to San Diego', null], blocks: [] },
    plan: null,
    expect: {
      aboutDay: true,
      changes: [{ kinds: ['add_block'], at: '13:00', travel: true }],
      forbid: ['skip_habit', 'move_day', 'cancel'],
      maxChanges: 2,
    },
  },
  {
    id: 'calendar-meeting',
    title: 'A calendar meeting cannot be moved here',
    look: 'Says plainly that the meeting lives in their calendar; no change pretends to move it.',
    today: '2026-10-02',
    at: '09:10',
    text: 'move timesheets to tomorrow',
    items: ALEX_ITEMS,
    meetings: [['16:00', '16:30', 'Timesheets']],
    record: { travel: ['Flying to San Diego', '12:30'], blocks: [['12:30', 'Leave for the airport', true]] },
    plan: null,
    expect: {
      aboutDay: true,
      status: ['not_possible'],
      forbid: ['create_todo', 'move_day', 'retime'],
      maxChanges: 0,
    },
  },
  {
    id: 'cancelled-appointment',
    title: '1 October: the appointment is off',
    look: 'Takes the prep todo off the list, nothing else.',
    today: '2026-10-01',
    at: '20:30',
    text: "the vet appointment got cancelled, Bella's fine",
    items: [
      { id: 'sample', kind: 'todo', title: "Get a sample for Bella's vet appointment", due_day: '2026-10-02', minutes: 10, note: 'upcoming' },
      { id: 'mum', kind: 'todo', title: 'Call Mum', due_day: '2026-10-02', minutes: 20, note: 'upcoming' },
    ],
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: {
      aboutDay: true,
      changes: [{ kinds: ['cancel', 'complete'], id: 'sample' }],
      forbid: ['cancel:mum', 'create_todo'],
      maxChanges: 1,
    },
  },
  {
    id: 'three-asks',
    title: 'Three asks in one message',
    look: 'All three on one card: skip the run, add sunscreen, pushups at 6pm.',
    today: '2026-10-02',
    at: '10:00',
    text: "skip my run today, add buy sunscreen, and I'll do pushups at 6pm",
    items: [
      { id: 'run', kind: 'habit', title: 'Run', minutes: 30, note: 'in the plan' },
      { id: 'pushups', kind: 'habit', title: 'Pushups', minutes: 10, note: 'habit today' },
    ],
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: { status: 'locked', items: [['run', '17:00', 30]] },
    expect: {
      aboutDay: true,
      changes: [
        { kinds: ['skip_habit', 'plan_remove'], id: 'run' },
        { kinds: ['create_todo'], title: 'sunscreen' },
        { kinds: ['retime', 'plan_add', 'plan_move'], id: 'pushups', at: '18:00' },
      ],
      maxChanges: 4,
    },
  },
  {
    id: 'deck-not-today',
    title: 'Something due later comes off today',
    look: 'Takes the deck out of today (plan or day), never marks it done.',
    today: '2026-10-02',
    at: '09:20',
    text: "the deck isn't due till Saturday, take it off today",
    items: [
      { id: 'deck', kind: 'todo', title: 'Send the partner deck', due_day: '2026-10-02', minutes: 60, note: 'in the plan' },
      { id: 'mum', kind: 'todo', title: 'Call Mum', due_day: '2026-10-02', minutes: 20, note: 'in the plan' },
    ],
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: { status: 'proposal', items: [['deck', '10:00', 60], ['mum', '11:50', 20]] },
    expect: {
      aboutDay: true,
      changes: [{ kinds: ['move_day', 'plan_remove'], id: 'deck' }],
      forbid: ['complete', 'cancel', 'plan_remove:mum'],
      maxChanges: 2,
    },
  },
  {
    id: 'not-about-the-day',
    title: 'A general question goes to normal chat',
    look: 'about_day is false.',
    today: '2026-10-02',
    at: '09:30',
    text: "what's the weather usually like in San Diego in October?",
    items: ALEX_ITEMS,
    meetings: [],
    record: { travel: ['Flying to San Diego', null], blocks: [] },
    plan: null,
    expect: { aboutDay: false },
  },
  {
    id: 'answers-the-question',
    title: "An answer to Gremly's question",
    look: 'Treated as about the day; no false claim; nothing invented.',
    today: '2026-10-02',
    at: '08:20',
    question: 'Is your haircut this Friday or Saturday?',
    text: 'Saturday at 10',
    items: ALEX_ITEMS,
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: { aboutDay: true, forbid: ['cancel', 'complete', 'move_day'], maxChanges: 1 },
  },
  {
    id: 'present-before-anniversary',
    title: 'A present for a date: due before it, never on it',
    look: 'Gremly asked when the anniversary is; the answer gives the present a day before the 10th, or Gremly asks when it should be ready. Never the 10th itself.',
    today: '2026-10-02',
    at: '18:30',
    history: [
      { role: 'user', content: "I need to sort Dave's anniversary present" },
      { role: 'assistant', content: "It's on your list already. When is your anniversary?" },
    ],
    text: "it's on the 10th",
    items: [
      { id: 'gift', kind: 'todo', title: 'Get Dave an anniversary present', minutes: 60, note: 'no day' },
      { id: 'mum', kind: 'todo', title: 'Call Mum', due_day: '2026-10-02', minutes: 20, note: 'due today' },
    ],
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: { aboutDay: true, dueBefore: { id: 'gift', before: '2026-10-10' }, forbid: ['cancel', 'complete'], maxChanges: 2 },
  },
  {
    id: 'present-for-a-date',
    title: 'Something to get ready for a date, said in one go',
    look: 'A todo for the present due before the 10th, or a question about when it should be ready. Never due on the 10th.',
    today: '2026-10-02',
    at: '12:15',
    text: 'add getting Sam a birthday present, her birthday is on the 10th',
    items: ALEX_ITEMS,
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: { aboutDay: true, dueBefore: { title: 'present', before: '2026-10-10' }, maxChanges: 2 },
  },
  {
    id: 'appointment-after-question',
    title: '3 October (live test): an appointment, its day and time given after Gremly asked',
    look: 'A card with the appointment on Thursday 8 October at 10:00, as a dated note or a todo with that day and time. Never a reply that it cannot be added.',
    today: '2026-10-03',
    at: '09:30',
    history: [
      { role: 'user', content: 'add a dentist appointment' },
      { role: 'assistant', content: 'What day and time is the dentist appointment?' },
    ],
    tasks: [{ ask: 'Add a dentist appointment', status: 'needs_answer' }],
    text: 'Thursday at 10am',
    items: SAT_ITEMS,
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: {
      aboutDay: true,
      changes: [{ kinds: ['create_todo'], day: '2026-10-08', at: '10:00' }],
      maxChanges: 1,
      maxModelCalls: 3,
    },
  },
  {
    id: 'gift-for-a-wedding',
    title: '3 October (live test): a gift for a wedding on the 17th',
    look: 'A todo for the gift on one day before the 17th, saying why, or a question about when. The wedding itself offered as well.',
    today: '2026-10-03',
    at: '09:30',
    text: "I need a gift for a friend's wedding on the 17th",
    items: SAT_ITEMS,
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: {
      aboutDay: true,
      dueBefore: { title: 'gift', before: '2026-10-17' },
      oneDate: true,
      offersEvent: { title: 'wedding', day: '2026-10-17' },
      maxChanges: 2,
      maxModelCalls: 3,
    },
  },
  {
    id: 'gift-new-event',
    title: 'A gift for a wedding on the 17th, with nothing like it on their list',
    look: 'A todo for the gift on one day before the 17th, saying why, or a question about when; the wedding itself offered on the 17th.',
    today: '2026-10-03',
    at: '09:30',
    text: "I need a gift for a friend's wedding on the 17th",
    items: SAT_ITEMS.filter((x) => x.id !== 'gift'),
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: {
      aboutDay: true,
      dueBefore: { title: 'gift', before: '2026-10-17' },
      oneDate: true,
      offersEvent: { title: 'wedding', day: '2026-10-17' },
      maxChanges: 2,
      maxModelCalls: 2,
    },
  },
  {
    id: 'plan-offer',
    title: 'No plan yet and not sure where to start: Gremly offers to plan the day',
    look: 'An offer to plan the rest of today on the card (plan_day), without waiting to be asked.',
    today: '2026-10-03',
    at: '09:30',
    text: "I've got a free morning and I'm not sure where to start",
    items: SAT_ITEMS,
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: {
      aboutDay: true,
      changes: [{ kinds: ['plan_day'] }],
      maxChanges: 1,
      maxModelCalls: 2,
    },
  },
  {
    id: 'week-ahead',
    title: '3 October (live test): what is on next week',
    look: 'The week from Monday to Sunday from their items, nothing invented, nothing on the card, without stopping part way.',
    today: '2026-10-03',
    at: '09:30',
    text: 'What do I have on next week?',
    items: SAT_ITEMS,
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: {
      aboutDay: true,
      maxChanges: 0,
      mentions: ['deck', 'qbr', 'vet'],
      maxModelCalls: 3,
    },
  },
  {
    id: 'move-a-todo',
    title: '3 October (live test): move one todo to another day',
    look: 'One row moving Do taxes to Monday 5 October, offered, in as few calls as possible.',
    today: '2026-10-03',
    at: '09:30',
    text: 'Can I move do taxes to Monday?',
    items: SAT_ITEMS,
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: {
      aboutDay: true,
      changes: [{ kinds: ['move_day'], id: 'taxes', day: '2026-10-05' }],
      maxChanges: 1,
      maxModelCalls: 2,
    },
  },
];
