/**
 * The day turn's replay suite: messages typed in today's thread, built on the
 * real 1 and 2 October mornings (with made-up names and items), and made-up
 * edge cases. Each says what the turn must and must not do.
 *
 * A scenario: today, at (HH:MM), text, question, history, items, meetings,
 * record ({ travel: [label, 'HH:MM' | null], blocks: [['HH:MM', title, travel]] }),
 * plan ({ status, items: [[id, 'HH:MM', minutes]] }), and expect:
 *   aboutDay        true or false
 *   changes         every one must be on the card: { kind (or kinds), id, at }
 *   forbid          kinds (or kind:id) that must not be on the card
 *   status          checklist statuses that must appear
 *   maxChanges      at most this many changes
 *   dueBefore       { id or title, before: YYYY-MM-DD }: what gets someone ready
 *                   for a later date is due before it, or Gremly asks (needs_answer)
 *   oneDate         a new todo has one date, unless the person named a deadline
 *   offersEvent     { title, day }: the event they mentioned is offered too (warn)
 *   mentions        words the reply should cover (warn)
 *   maxModelCalls   at most this many model calls for the message (warn)
 *   planAddsUntimed plan_add carries no time (they named none; the app finds one)
 *   planFrom        'HH:MM': no plan time before it
 *   planAddsFrom    'HH:MM': every plan_add carries a time at or after it (warn)
 * A scenario may also carry tasks: Gremly's task list so far in the thread.
 */

const ALEX_ITEMS = [
  { id: 'mum', kind: 'todo', title: 'Call Mum', due_day: '2026-10-02', minutes: 20, note: 'in the plan' },
  { id: 'deck', kind: 'todo', title: 'Send the partner deck', due_day: '2026-10-03', minutes: 60, note: 'upcoming' },
  { id: 'present', kind: 'todo', title: 'Find a present for Sam', due_day: '2026-10-02', minutes: 45, note: 'in the plan' },
  { id: 'calendar', kind: 'todo', title: 'Set up the shared calendar', due_day: '2026-10-02', minutes: 20, note: 'due today' },
  { id: 'pushups', kind: 'habit', title: 'Pushups', minutes: 10, note: 'habit today' },
];


const VET_VISIT = { id: 'vetvisit', kind: 'todo', title: 'Take Bella to the vet', due_day: '2026-10-09', minutes: 60, note: 'upcoming' };

const SAT_ITEMS = [
  { id: 'taxes', kind: 'todo', title: 'Do taxes', due_day: '2026-10-03', minutes: 60, note: 'due today' },
  { id: 'flowers', kind: 'todo', title: 'Water the plants', due_day: '2026-10-04', minutes: 10, note: 'upcoming' },
  { id: 'deck', kind: 'todo', title: 'Send the partner deck', due_day: '2026-10-05', minutes: 60, note: 'upcoming' },
  { id: 'gift', kind: 'todo', title: 'Find a present for Sam', due_day: '2026-10-05', minutes: 45, note: 'upcoming' },
  { id: 'qbr', kind: 'todo', title: 'Schedule the QBR', due_day: '2026-10-08', minutes: 20, note: 'upcoming' },
  { id: 'vet', kind: 'todo', title: 'Book the vet for Bella', due_day: '2026-10-09', minutes: 15, note: 'upcoming' },
  { id: 'pushups', kind: 'habit', title: 'Pushups', minutes: 10, note: 'habit today' },
];

// a reply that tells them nothing changes, instead of taking in what they said
const NO_CHANGE_TALK =
  "(doesn'?t|does not|won'?t) change|changes? nothing|no changes?\\b|nothing (needs|has) to (change|move)|nothing needs (changing|moving)|(items|plans) (need|as they are)|need changing";

// a Monday morning with a long list due today (built on 5 October, made-up items)
const MONDAY_ITEMS = [
  { id: 'workback', kind: 'todo', title: 'Build a launch work-back schedule', due_day: '2026-10-05', minutes: 45, note: 'in the plan' },
  { id: 'gift', kind: 'todo', title: 'Find a present for Sam', due_day: '2026-10-05', minutes: 30, note: 'in the plan' },
  { id: 'submit', kind: 'todo', title: 'Submit the app for review', due_day: '2026-10-05', minutes: 90, note: 'in the plan' },
  { id: 'strength', kind: 'habit', title: 'Strength training', minutes: 45, note: 'in the plan' },
  { id: 'cycle', kind: 'habit', title: 'Cycling', minutes: 30, note: 'in the plan' },
  { id: 'taxes', kind: 'todo', title: 'Do taxes', due_day: '2026-10-05', minutes: 60, note: 'in the plan, added by them' },
  { id: 'intention', kind: 'todo', title: 'Add the weekly intention to the brief', due_day: '2026-10-05', minutes: 10, note: 'due today' },
  { id: 'agent', kind: 'todo', title: 'Move chat over to the agent', due_day: '2026-10-05', minutes: 45, note: 'due today' },
  { id: 'inputbox', kind: 'todo', title: 'Fix the input box clearing', due_day: '2026-10-05', minutes: 30, note: 'due today' },
  { id: 'splitcheck', kind: 'todo', title: 'Check split drops still work', due_day: '2026-10-05', minutes: 15, note: 'due today' },
  { id: 'hotel', kind: 'todo', title: 'Book the hotel for the Lisbon trip', due_day: '2026-10-05', minutes: 30, note: 'due today' },
  { id: 'trip', kind: 'todo', title: 'Sort out the Japan trip', due_day: '2026-10-05', minutes: 60, note: 'due today' },
  { id: 'tennis', kind: 'todo', title: 'Look into a tennis weekend', due_day: '2026-10-05', minutes: 60, note: 'due today' },
  { id: 'tap', kind: 'todo', title: 'Fix the bathroom tap', due_day: '2026-10-05', minutes: 45, note: 'due today' },
  { id: 'logos', kind: 'todo', title: 'Add logos to the website', due_day: '2026-10-05', minutes: 30, note: 'due today' },
];

const MONDAY_MEETINGS = [
  ['06:00', '06:30', 'Design sync'],
  ['07:30', '08:00', 'Product sync'],
  ['08:00', '08:30', 'Team huddle'],
  ['11:15', '12:00', 'Client call'],
  ['12:30', '13:00', 'Budget review'],
  ['13:30', '14:00', 'Weekly 1:1'],
];

// the thread so far on that Monday morning, before the plan was changed
const MONDAY_HISTORY = [
  { role: 'assistant', content: 'Good morning Alex. You have syncs running through early this morning, wrapping up with the team huddle at 8am.' },
  { role: 'assistant', content: 'After 8:30am your calendar is open, leaving room for the work-back schedule, a present for Sam, or submitting the app.' },
  { role: 'user', content: 'I actually have meetings from 11.15 to 12, then 12.30 to 1 and 1.30 to 2' },
  { role: 'assistant', content: "Got it, I'd block those three meetings into today so the plan works around them." },
  { role: 'user', content: "(On Gremly's card they accepted: set time today Meeting at 11:15am to 12pm; set time today Meeting at 12:30pm to 1pm; set time today Meeting at 1:30pm to 2pm.)" },
  { role: 'user', content: 'Plan my day' },
  { role: 'assistant', content: "I've made room for the launch path, the present and the submission, while keeping the rest of the day open." },
];

const MONDAY_PLAN = {
  status: 'proposal',
  items: [
    ['workback', '08:45', 45],
    ['gift', '10:00', 30],
    ['submit', '14:15', 90],
    ['strength', '16:00', 45],
    ['cycle', '17:00', 30],
    ['taxes', '17:45', 60],
  ],
};

export const SCENARIOS = [
  {
    id: 'airport-and-call',
    title: '2 October: a call at 12 and leaving for the airport at 12:30',
    look: 'One card: Call Mum moves to 12:00 and a set time "leave for the airport" at 12:30 (travel). No claim that anything is done.',
    today: '2026-10-02',
    at: '09:04',
    text: 'I need to call my parents at 12 and then leave for the airport at 12:30',
    items: ALEX_ITEMS,
    meetings: [
      ['08:00', '08:30', 'Team huddle'],
      ['16:00', '16:30', 'Timesheets'],
    ],
    record: { travel: ['Flying to San Diego', null], blocks: [] },
    plan: {
      status: 'proposal',
      items: [
        ['present', '09:30', 45],
        ['mum', '11:50', 20],
      ],
    },
    expect: {
      aboutDay: true,
      changes: [
        { kinds: ['retime', 'plan_move'], id: 'mum', at: '12:00' },
        { kinds: ['add_block'], at: '12:30', travel: true },
      ],
      forbid: ['create_todo'],
      maxChanges: 3,
    },
  },
  {
    id: 'flying-today',
    title: '2 October (the other side): "we fly today" with no time yet',
    look: 'Asks when they set off or proposes nothing it cannot know; never moves or skips a habit it was not asked about.',
    today: '2026-10-02',
    at: '08:07',
    text: "we're flying to San Diego today, can you plan around that?",
    items: [
      { id: 'workout', kind: 'habit', title: 'Work out', minutes: 30, note: 'habit today' },
      { id: 'card', kind: 'todo', title: 'Buy an anniversary card', due_day: '2026-10-07', minutes: 15, note: 'upcoming' },
      { id: 'pack', kind: 'todo', title: 'Pack', due_day: '2026-10-02', minutes: 30, note: 'due today' },
    ],
    meetings: [],
    record: { travel: ['Flying to San Diego', null], blocks: [] },
    plan: null,
    expect: {
      aboutDay: true,
      forbid: ['skip_habit', 'move_day:workout', 'retime:workout', 'cancel'],
      status: ['needs_answer'],
      maxChanges: 1,
    },
  },
  {
    id: 'flying-at-three',
    title: 'Flying at 3, leaving at 1',
    look: 'A travel set time at 13:00; nothing moved that was not asked for.',
    today: '2026-10-02',
    at: '08:10',
    text: 'our flight is at 3, we leave the house at 1',
    items: [
      { id: 'workout', kind: 'habit', title: 'Work out', minutes: 30, note: 'habit today' },
      { id: 'pack', kind: 'todo', title: 'Pack', due_day: '2026-10-02', minutes: 30, note: 'due today' },
    ],
    meetings: [],
    record: { travel: ['Flying to San Diego', null], blocks: [] },
    plan: null,
    expect: {
      aboutDay: true,
      changes: [{ kinds: ['add_block'], at: '13:00', travel: true }],
      forbid: ['skip_habit', 'move_day', 'cancel'],
      maxChanges: 2,
    },
  },
  {
    id: 'calendar-meeting',
    title: 'A calendar meeting cannot be moved here',
    look: 'Says plainly that the meeting lives in their calendar; no change pretends to move it.',
    today: '2026-10-02',
    at: '09:10',
    text: 'move timesheets to tomorrow',
    items: ALEX_ITEMS,
    meetings: [['16:00', '16:30', 'Timesheets']],
    record: { travel: ['Flying to San Diego', '12:30'], blocks: [['12:30', 'Leave for the airport', true]] },
    plan: null,
    expect: {
      aboutDay: true,
      status: ['not_possible'],
      forbid: ['create_todo', 'move_day', 'retime'],
      maxChanges: 0,
    },
  },
  {
    id: 'cancelled-appointment',
    title: '1 October: the appointment is off',
    look: 'Takes the prep todo off the list, nothing else.',
    today: '2026-10-01',
    at: '20:30',
    text: "the vet appointment got cancelled, Bella's fine",
    items: [
      { id: 'sample', kind: 'todo', title: "Get a sample for Bella's vet appointment", due_day: '2026-10-02', minutes: 10, note: 'upcoming' },
      { id: 'mum', kind: 'todo', title: 'Call Mum', due_day: '2026-10-02', minutes: 20, note: 'upcoming' },
    ],
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: {
      aboutDay: true,
      changes: [{ kinds: ['cancel', 'complete'], id: 'sample' }],
      forbid: ['cancel:mum', 'create_todo'],
      maxChanges: 1,
    },
  },
  {
    id: 'three-asks',
    title: 'Three asks in one message',
    look: 'All three on one card: skip the run, add sunscreen, pushups at 6pm.',
    today: '2026-10-02',
    at: '10:00',
    text: "skip my run today, add buy sunscreen, and I'll do pushups at 6pm",
    items: [
      { id: 'run', kind: 'habit', title: 'Run', minutes: 30, note: 'in the plan' },
      { id: 'pushups', kind: 'habit', title: 'Pushups', minutes: 10, note: 'habit today' },
    ],
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: { status: 'locked', items: [['run', '17:00', 30]] },
    expect: {
      aboutDay: true,
      changes: [
        { kinds: ['skip_habit', 'plan_remove'], id: 'run' },
        { kinds: ['create_todo'], title: 'sunscreen' },
        { kinds: ['retime', 'plan_add', 'plan_move'], id: 'pushups', at: '18:00' },
      ],
      maxChanges: 4,
    },
  },
  {
    id: 'deck-not-today',
    title: 'Something due later comes off today',
    look: 'Takes the deck out of today (plan or day), never marks it done.',
    today: '2026-10-02',
    at: '09:20',
    text: "the deck isn't due till Saturday, take it off today",
    items: [
      { id: 'deck', kind: 'todo', title: 'Send the partner deck', due_day: '2026-10-02', minutes: 60, note: 'in the plan' },
      { id: 'mum', kind: 'todo', title: 'Call Mum', due_day: '2026-10-02', minutes: 20, note: 'in the plan' },
    ],
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: { status: 'proposal', items: [['deck', '10:00', 60], ['mum', '11:50', 20]] },
    expect: {
      aboutDay: true,
      changes: [{ kinds: ['move_day', 'plan_remove'], id: 'deck' }],
      forbid: ['complete', 'cancel', 'plan_remove:mum'],
      maxChanges: 2,
    },
  },
  {
    id: 'not-about-the-day',
    title: 'A general question goes to normal chat',
    look: 'about_day is false.',
    today: '2026-10-02',
    at: '09:30',
    text: "what's the weather usually like in San Diego in October?",
    items: ALEX_ITEMS,
    meetings: [],
    record: { travel: ['Flying to San Diego', null], blocks: [] },
    plan: null,
    expect: { aboutDay: false },
  },
  {
    id: 'answers-the-question',
    title: "An answer to Gremly's question",
    look: 'Treated as about the day; no false claim; nothing invented.',
    today: '2026-10-02',
    at: '08:20',
    question: 'Is your haircut this Friday or Saturday?',
    text: 'Saturday at 10',
    items: ALEX_ITEMS,
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: { aboutDay: true, forbid: ['cancel', 'complete', 'move_day'], maxChanges: 1 },
  },
  {
    id: 'wrap-asks-mid-sweep',
    title: 'A question typed half way through the evening wrap up',
    look: 'Answers about tomorrow from what it knows; nothing on the card; does not start the wrap up again.',
    today: '2026-10-03',
    at: '20:40',
    text: "What's on tomorrow?",
    wrap: { step: 'habits', decisions: [{ title: 'Do taxes', outcome: 'kept for tomorrow' }] },
    items: SAT_ITEMS,
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: { aboutDay: true, maxChanges: 0 },
  },
  {
    id: 'wrap-answer-fixes-item',
    title: "The wrap up's question answered, and the item is wrong",
    look: 'Takes the answer in, and puts the vet visit on Monday on the card.',
    today: '2026-10-03',
    at: '20:50',
    text: 'Monday',
    wrap: {
      step: 'questions',
      decisions: [],
      answering: {
        question: "Is Bella's vet visit on Friday 9 October or Monday 12 October?",
        item: { id: 'vetvisit', kind: 'todo', title: 'Take Bella to the vet', when: 'Fri 9 Oct' },
      },
    },
    items: [...SAT_ITEMS, VET_VISIT],
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: { aboutDay: true, changes: [{ kinds: ['move_day'], id: 'vetvisit', day: '2026-10-12' }], maxChanges: 1 },
  },
  {
    id: 'wrap-answer-no-change',
    title: "The wrap up's question answered, and the item is right",
    look: 'Takes the answer in as a friend would, without announcing that nothing changes; nothing on the card.',
    today: '2026-10-03',
    at: '20:50',
    text: 'Friday',
    wrap: {
      step: 'questions',
      decisions: [],
      answering: {
        question: "Is Bella's vet visit on Friday 9 October or Monday 12 October?",
        item: { id: 'vetvisit', kind: 'todo', title: 'Take Bella to the vet', when: 'Fri 9 Oct' },
      },
    },
    items: [...SAT_ITEMS, VET_VISIT],
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: {
      aboutDay: true,
      maxChanges: 0,
      notSaidLike: [NO_CHANGE_TALK],
    },
  },
  {
    id: 'wrap-answer-life',
    title: "The wrap up's question answered about their life",
    look: 'A warm reply that takes the answer in; at most an offer of a todo for what they said they need to do; nothing moved, done or cancelled.',
    today: '2026-10-03',
    at: '20:55',
    text: 'Still unsure to be honest. Need to talk to Jo and look at flights',
    wrap: {
      step: 'questions',
      decisions: [],
      answering: { question: "Are you leaning towards going to Sam's 40th in London on 24 October?" },
    },
    items: SAT_ITEMS,
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: {
      aboutDay: true,
      forbid: ['cancel', 'complete', 'move_day'],
      maxChanges: 1,
      notSaidLike: [NO_CHANGE_TALK],
    },
  },
  {
    id: 'present-before-anniversary',
    title: 'A present for a date: due before it, never on it',
    look: 'Gremly asked when the anniversary is; the answer gives the present a day before the 10th, or Gremly asks when it should be ready. Never the 10th itself.',
    today: '2026-10-02',
    at: '18:30',
    history: [
      { role: 'user', content: "I need to sort Dave's anniversary present" },
      { role: 'assistant', content: "It's on your list already. When is your anniversary?" },
    ],
    text: "it's on the 10th",
    items: [
      { id: 'gift', kind: 'todo', title: 'Get Dave an anniversary present', minutes: 60, note: 'no day' },
      { id: 'mum', kind: 'todo', title: 'Call Mum', due_day: '2026-10-02', minutes: 20, note: 'due today' },
    ],
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: { aboutDay: true, dueBefore: { id: 'gift', before: '2026-10-10' }, forbid: ['cancel', 'complete'], maxChanges: 2 },
  },
  {
    id: 'present-for-a-date',
    title: 'Something to get ready for a date, said in one go',
    look: 'A todo for the present due before the 10th, or a question about when it should be ready. Never due on the 10th.',
    today: '2026-10-02',
    at: '12:15',
    text: 'add getting Sam a birthday present, her birthday is on the 10th',
    items: ALEX_ITEMS,
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: { aboutDay: true, dueBefore: { title: 'present', before: '2026-10-10' }, maxChanges: 2 },
  },
  {
    id: 'appointment-after-question',
    title: '3 October (live test): an appointment, its day and time given after Gremly asked',
    look: 'A card with the appointment on Thursday 8 October at 10:00, as a dated note or a todo with that day and time. Never a reply that it cannot be added.',
    today: '2026-10-03',
    at: '09:30',
    history: [
      { role: 'user', content: 'add a dentist appointment' },
      { role: 'assistant', content: 'What day and time is the dentist appointment?' },
    ],
    tasks: [{ ask: 'Add a dentist appointment', status: 'needs_answer' }],
    text: 'Thursday at 10am',
    items: SAT_ITEMS,
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: {
      aboutDay: true,
      changes: [{ kinds: ['create_todo'], day: '2026-10-08', at: '10:00' }],
      maxChanges: 1,
      maxModelCalls: 3,
    },
  },
  {
    id: 'gift-for-a-wedding',
    title: '3 October (live test): a gift for a wedding on the 17th',
    look: 'A todo for the gift on one day before the 17th, saying why, or a question about when. The wedding itself offered as well.',
    today: '2026-10-03',
    at: '09:30',
    text: "I need a gift for a friend's wedding on the 17th",
    items: SAT_ITEMS,
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: {
      aboutDay: true,
      dueBefore: { title: 'gift', before: '2026-10-17' },
      oneDate: true,
      offersEvent: { title: 'wedding', day: '2026-10-17' },
      maxChanges: 2,
      maxModelCalls: 3,
    },
  },
  {
    id: 'gift-new-event',
    title: 'A gift for a wedding on the 17th, with nothing like it on their list',
    look: 'A todo for the gift on one day before the 17th, saying why, or a question about when; the wedding itself offered on the 17th.',
    today: '2026-10-03',
    at: '09:30',
    text: "I need a gift for a friend's wedding on the 17th",
    items: SAT_ITEMS.filter((x) => x.id !== 'gift'),
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: {
      aboutDay: true,
      dueBefore: { title: 'gift', before: '2026-10-17' },
      oneDate: true,
      offersEvent: { title: 'wedding', day: '2026-10-17' },
      maxChanges: 2,
      maxModelCalls: 2,
    },
  },
  {
    id: 'plan-offer',
    title: 'No plan yet and not sure where to start: Gremly offers to plan the day',
    look: 'An offer to plan the rest of today on the card (plan_day), without waiting to be asked.',
    today: '2026-10-03',
    at: '09:30',
    text: "I've got a free morning and I'm not sure where to start",
    items: SAT_ITEMS,
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: {
      aboutDay: true,
      changes: [{ kinds: ['plan_day'] }],
      maxChanges: 1,
      maxModelCalls: 2,
    },
  },
  {
    id: 'anniversary-evening',
    title: '3 October (live test): the evening plans on an anniversary weekend',
    look: 'The show and the dinner on the card at their times, and a reply that shares in the anniversary the day is about.',
    today: '2026-10-03',
    at: '10:55',
    text: 'We have the comedy show at 6pm and then I think we are going to have dinner at the hotel from say 8.30ish',
    items: SAT_ITEMS,
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: { status: 'proposal', items: [['taxes', '15:00', 60]] },
    dco: {
      lead_story: {
        what: 'Anniversary weekend with Sam in San Diego',
        why_today: 'A multi-day trip celebrating their anniversary, running through Sunday.',
      },
      day_frame: { away: { label: 'San Diego anniversary trip', through: '2026-10-04' } },
      voice_note: 'Keep things warm, unhurried, and supportive of them enjoying the trip.',
    },
    expect: {
      aboutDay: true,
      changes: [
        { kinds: ['add_block', 'create_todo'], at: '18:00' },
        { kinds: ['add_block', 'create_todo'], at: '20:30' },
      ],
      mentions: ['anniversary'],
      maxChanges: 3,
      maxModelCalls: 2,
    },
  },
  {
    id: 'left-out-stays-out',
    title: '3 October (live test): what they left out on a card is not offered again',
    look: 'A run fitted in, with nothing they left out on the last card offered again.',
    today: '2026-10-03',
    at: '10:49',
    history: [
      { role: 'user', content: "I listened to Blinkist this morning. I probably won't have time for anything else today." },
      { role: 'assistant', content: "I'd log Blinkist for this morning and take Do taxes and the partner deck out of today's plan." },
      {
        role: 'user',
        content:
          "(On Gremly's card they accepted: Log Blinkist for Sat 3 Oct. They left out: Take Do taxes out of today's plan; Take Send the partner deck out of today's plan.)",
      },
    ],
    text: "Let's aim for a run with Sam today",
    items: [
      ...SAT_ITEMS.map((x) => (x.id === 'deck' ? { ...x, due_day: '2026-10-03', note: 'in the plan' } : x)),
      { id: 'run', kind: 'habit', title: 'Run', minutes: 45, note: 'habit today' },
    ],
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: { status: 'proposal', items: [['deck', '13:00', 60], ['taxes', '15:00', 60]] },
    expect: {
      aboutDay: true,
      forbid: ['plan_remove:taxes', 'plan_remove:deck', 'move_day:taxes', 'move_day:deck'],
      maxModelCalls: 2,
    },
  },
  {
    id: 'week-ahead',
    title: '3 October (live test): what is on next week',
    look: 'The week from Monday to Sunday from their items, nothing invented, nothing on the card, without stopping part way.',
    today: '2026-10-03',
    at: '09:30',
    text: 'What do I have on next week?',
    items: SAT_ITEMS,
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: {
      aboutDay: true,
      maxChanges: 0,
      mentions: ['deck', 'qbr', 'vet'],
      maxModelCalls: 3,
    },
  },
  {
    id: 'move-a-todo',
    title: '3 October (live test): move one todo to another day',
    look: 'One row moving Do taxes to Monday 5 October, offered, in as few calls as possible.',
    today: '2026-10-03',
    at: '09:30',
    text: 'Can I move do taxes to Monday?',
    items: SAT_ITEMS,
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: {
      aboutDay: true,
      changes: [{ kinds: ['move_day'], id: 'taxes', day: '2026-10-05' }],
      maxChanges: 1,
      maxModelCalls: 2,
    },
  },
  {
    id: 'late-call-this-afternoon',
    title: 'After midnight (still Saturday until 3am): something for the afternoon',
    look: 'Their afternoon is Sunday afternoon: a new todo on Sunday 4 October, never a set time on Saturday.',
    today: '2026-10-03',
    at: '01:20',
    text: 'I need to call mum this afternoon',
    items: SAT_ITEMS,
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: { aboutDay: true, changes: [{ kinds: ['create_todo'], day: '2026-10-04' }], forbid: ['add_block'], maxChanges: 1 },
  },
  {
    id: 'late-taxes-in-the-morning',
    title: 'After midnight: moving something to the morning',
    look: 'The morning is Sunday morning: Do taxes moves to Sunday 4 October.',
    today: '2026-10-03',
    at: '00:40',
    text: "I'm not doing taxes tonight, I'll do them in the morning",
    items: SAT_ITEMS,
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: { aboutDay: true, changes: [{ kinds: ['move_day'], id: 'taxes', day: '2026-10-04' }], maxChanges: 1 },
  },
  {
    id: 'late-already-tomorrow',
    title: 'After midnight: tomorrow is the day after their Saturday',
    look: 'Water the plants is already on Sunday, their tomorrow: nothing to move, and he says so.',
    today: '2026-10-03',
    at: '01:50',
    text: 'Move water the plants to tomorrow',
    items: SAT_ITEMS,
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: { aboutDay: true, forbid: ['move_day'], maxChanges: 0 },
  },
  {
    id: 'late-whats-tomorrow',
    title: 'After midnight: what is on tomorrow',
    look: 'Tomorrow is Sunday: the plants. Nothing that is on Monday is named as tomorrow.',
    today: '2026-10-03',
    at: '00:30',
    text: 'What have I got on tomorrow?',
    items: SAT_ITEMS,
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: { aboutDay: true, maxChanges: 0, mentions: ['plants'], notSaid: ['deck', 'present'] },
  },
  {
    id: 'wrap-undo-move',
    title: 'During the wrap up: put back a card they moved',
    look: 'Send the partner deck goes back to Monday 5 October, where it was before tonight.',
    today: '2026-10-03',
    at: '21:10',
    text: 'Actually can you put the deck back where it was',
    wrap: {
      step: 'journal',
      decisions: [
        { id: 'deck', type: 'todo', title: 'Send the partner deck', outcome: 'kept for Friday', was: 'was due Monday 5 October' },
        { id: 'taxes', type: 'todo', title: 'Do taxes', outcome: 'kept for tomorrow', was: 'was due Saturday 3 October' },
      ],
    },
    items: SAT_ITEMS.map((x) => (x.id === 'deck' ? { ...x, due_day: '2026-10-09' } : x.id === 'taxes' ? { ...x, due_day: '2026-10-04', note: 'upcoming' } : x)),
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: { aboutDay: true, changes: [{ kinds: ['move_day'], id: 'deck', day: '2026-10-05' }], maxChanges: 1 },
  },
  {
    id: 'wrap-undo-let-go',
    title: 'During the wrap up: bring back one they let go',
    look: 'Schedule the QBR, let go tonight, is restored.',
    today: '2026-10-03',
    at: '21:12',
    text: "Oh no, I didn't mean to let the QBR one go",
    wrap: {
      step: 'habits',
      decisions: [{ id: 'qbr', type: 'todo', title: 'Schedule the QBR', outcome: 'let go' }],
    },
    items: SAT_ITEMS.map((x) => (x.id === 'qbr' ? { ...x, archived: true, note: '' } : x)),
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: { aboutDay: true, changes: [{ kinds: ['restore'], id: 'qbr' }], maxChanges: 2 },
  },
  {
    id: 'wrap-undo-later',
    title: 'During the wrap up: one they sent to a later night, wanted tomorrow',
    look: 'Book the vet for Bella, set to come back on Monday, gets tomorrow (Sunday 4 October) as its day.',
    today: '2026-10-03',
    at: '21:15',
    text: 'Bring the vet one back for tomorrow instead',
    wrap: {
      step: 'journal',
      decisions: [{ id: 'vet', type: 'todo', title: 'Book the vet for Bella', outcome: 'to come back on Monday', was: 'was due Friday 9 October' }],
    },
    items: SAT_ITEMS,
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: { aboutDay: true, changes: [{ kinds: ['move_day'], id: 'vet', day: '2026-10-04' }], maxChanges: 1 },
  },
  {
    id: 'wrap-done-what-happened',
    title: 'After the wrap up: what happened to a card',
    look: 'Says the deck was moved to Friday tonight; nothing on the card.',
    today: '2026-10-03',
    at: '22:30',
    text: 'What did I do with the deck card tonight?',
    wrap: {
      step: 'done',
      decisions: [
        { id: 'deck', type: 'todo', title: 'Send the partner deck', outcome: 'kept for Friday', was: 'was due Monday 5 October' },
      ],
    },
    items: SAT_ITEMS.map((x) => (x.id === 'deck' ? { ...x, due_day: '2026-10-09' } : x)),
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: null,
    expect: { aboutDay: true, maxChanges: 0, mentions: ['friday'] },
  },
  {
    id: 'breaking-habit-not-planned',
    title: 'A habit they are breaking is never put in the plan',
    look: 'Adds what is left of today to the plan. No sugar, a habit they are breaking, is given no place in it.',
    today: '2026-10-02',
    at: '10:00',
    text: 'Add everything else I have on today to the plan',
    items: [
      { id: 'mum', kind: 'todo', title: 'Call Mum', due_day: '2026-10-02', minutes: 20, note: 'in the plan' },
      { id: 'calendar', kind: 'todo', title: 'Set up the shared calendar', due_day: '2026-10-02', minutes: 20, note: 'due today' },
      { id: 'pushups', kind: 'habit', title: 'Pushups', minutes: 10, note: 'habit today' },
      { id: 'sugar', kind: 'habit', title: 'No sugar', note: 'a habit they are breaking', breaking: true },
    ],
    meetings: [],
    record: { travel: null, blocks: [] },
    plan: { status: 'proposal', items: [['mum', '11:00', 20]] },
    expect: { aboutDay: true, changes: [{ kinds: ['plan_add'], id: 'calendar' }], forbid: ['plan_add:sugar'] },
  },
  {
    id: 'fill-the-day',
    title: '5 October, 7:35am: a plan on screen, and they ask Gremly to fill the free time',
    look: 'Adds a few of their todos to the plan with no times of its own (the app finds the free time). Nothing before 7:35am, nothing taken out.',
    today: '2026-10-05',
    at: '07:35',
    history: MONDAY_HISTORY,
    text: "I've got a ton of free time, can you fill it with more todos?",
    items: MONDAY_ITEMS,
    meetings: MONDAY_MEETINGS,
    record: { travel: null, blocks: [] },
    plan: MONDAY_PLAN,
    expect: { aboutDay: true, changes: [{ kinds: ['plan_add'] }], forbid: ['plan_remove'], planAddsUntimed: true },
  },
  {
    id: 'fill-the-evening',
    title: '5 October, 7:37am: they point Gremly at the open evening',
    look: 'Adds todos for after 5pm: either with no time, or at 5pm or later. Nothing before 5pm, nothing taken out.',
    today: '2026-10-05',
    at: '07:37',
    history: [
      ...MONDAY_HISTORY,
      { role: 'user', content: "I've got a ton of free time, can you fill it with more todos?" },
      { role: 'assistant', content: "Absolutely, there's plenty to choose from. I'd add a few more focused tasks around your meetings." },
      { role: 'user', content: "(On Gremly's card they accepted: add Move chat over to the agent to the plan; add Fix the input box clearing to the plan.)" },
    ],
    text: "There's 5 hours of room after 5pm, why aren't you using that time?",
    items: MONDAY_ITEMS,
    meetings: MONDAY_MEETINGS,
    record: { travel: null, blocks: [] },
    plan: MONDAY_PLAN,
    expect: { aboutDay: true, changes: [{ kinds: ['plan_add'] }], forbid: ['plan_remove'], planFrom: '17:00', planAddsFrom: '17:00' },
  },
];
