/** Shared shapes for the evening wrap up's cards, in the brief's colours. */
import { StyleSheet } from 'react-native';
import { BRIEF } from '../brief/briefStyles';

export const wrapStyles = StyleSheet.create({
  card: {
    backgroundColor: BRIEF.white,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: BRIEF.line,
    padding: 16,
    gap: 10,
  },
  head: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  title: { fontFamily: 'Inter-SemiBold', fontSize: 16, color: BRIEF.mossInk },
  hint: { fontFamily: 'Inter-Regular', fontSize: 12.5, color: BRIEF.faint },
  kicker: {
    fontFamily: 'Inter-SemiBold',
    fontSize: 11,
    letterSpacing: 1,
    color: BRIEF.faint,
    textTransform: 'uppercase',
  },
  tag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
    backgroundColor: BRIEF.sageWash,
  },
  tagText: { fontFamily: 'Inter-SemiBold', fontSize: 11, color: BRIEF.moss },
  row: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 6 },
  rowBody: { flex: 1, minWidth: 0 },
  rowTitle: { fontFamily: 'Inter-SemiBold', fontSize: 14.5, color: BRIEF.mossInk },
  rowSub: { fontFamily: 'Inter-Regular', fontSize: 12.5, color: BRIEF.muted, marginTop: 1 },
  box: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: BRIEF.chipBorder,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: BRIEF.white,
  },
  boxOn: { backgroundColor: BRIEF.moss, borderColor: BRIEF.moss },
  actions: { flexDirection: 'row', gap: 10, marginTop: 4 },
  btn: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    paddingVertical: 11,
    paddingHorizontal: 18,
  },
  btnGrow: { flex: 1 },
  btnPrimary: { backgroundColor: BRIEF.moss },
  btnSecondary: { borderWidth: 1.5, borderColor: BRIEF.chipBorder, backgroundColor: BRIEF.white },
  btnOff: { opacity: 0.5 },
  btnText: { fontFamily: 'Inter-SemiBold', fontSize: 14, color: BRIEF.moss },
  btnTextPrimary: { color: BRIEF.white },
  collapsed: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: BRIEF.chipBorder,
  },
  collapsedText: { fontFamily: 'Inter-Regular', fontSize: 13, color: BRIEF.faint },
  // Gremly's short line under a card, with its Undo
  closing: { fontFamily: 'Inter-Regular', fontSize: 15, lineHeight: 22, color: BRIEF.mossInk },
  undo: {
    fontFamily: 'Inter-SemiBold',
    fontSize: 13.5,
    color: BRIEF.moss,
    textDecorationLine: 'underline',
  },
  divider: { height: 1, backgroundColor: BRIEF.line, marginVertical: 2 },
});
