import type {
  AppRecord,
  CanonicalType,
  Todo,
  ID,
  Frequency,
  Note,
  NoteSubtype,
  HabitSubtype,
  Space,
  Tag,
  Person,
  EntityType,
  LegacyCanonicalType,
  TagsMeta,
} from '../types';
import type { SpaceInsert } from '../schemas';

/**
 * Input for creating a new record.
 * Note: owner_id, id, created_at, updated_at are auto-generated by the database.
 */
export interface CreateRecordInput {
  type: AppRecord['type'];
  name?: string; // For habits (Phase 7+) and todos (Phase 7+)
  title?: string; // For todos and notes
  body?: string;
  subtype?: NoteSubtype | HabitSubtype | 'reminder' | 'microproject' | null; // required for notes, optional for habits, AI-only for todos
  frequency?: Frequency; // required when type === 'habit'
  space_id?: ID | null;
  due_date?: string | null;
  undefined_due?: boolean; // for todos
  ai_placed?: boolean;
  why_string?: string | null;
  origin?: 'catchall' | 'space_chat' | 'manual';
  canonicalType?: CanonicalType | LegacyCanonicalType;
  sourceMessageId?: string | null; // For chat conversion tracking
  dropId?: string | null; // Mind Drop identifier for idempotent conversions
  labels?: string[];
  tags?: string[] | null; // Searchable tag slugs persisted with record
  tags_meta?: TagsMeta | null;
  views?: {
    alsoShowIn?: string[];
    ai_pending?: boolean; // Phase 1: Mind Drop AI processing state
    [key: string]: any; // Allow additional view state
  };
  // owner_id is optional - Supabase will set from auth context, Memory repo will use constructor userId
  owner_id?: ID;

  // Extended habit fields (Phase 7+)
  frequency_value?: any; // FrequencyValue JSON
  reminders?: any[]; // ReminderRow[] JSON
  notes?: string | null;
  buddy_id?: ID | null;
  buddy_email?: string | null;
  stack_with_id?: ID | null;
  stack_position?: 'before' | 'after' | null;
  stack_offset_minutes?: number | null;
  start_date?: string | null; // ISO date
  end_date?: string | null; // ISO date
  taper_plan?: any | null; // TaperPlanState JSON
  triggers?: string[] | null;
  replacement_habit_id?: ID | null;
  replacement_text?: string | null;

  // Extended todo fields (Phase 7+)
  due_time?: string | null; // HH:mm format for time due

  // Extended journal/note fields (Phase 7+) - only used when subtype='journal'
  date?: string | null; // ISO date for journal entry
  mood?: 'ecstatic' | 'happy' | 'neutral' | 'low' | 'sad' | 'tired' | null;
  fmt?: 'bullets' | 'numbers' | 'checkboxes' | null; // Formatting style
  journal_subtype?: 'reflection' | 'gratitude' | 'dream' | 'review' | null; // AI-only
}

/**
 * Input for updating an existing record
 */
export interface UpdateRecordInput {
  id: ID;
  patch: Partial<Omit<AppRecord, 'id' | 'type' | 'created_at' | 'owner_id'>> & {
    tags?: string[] | null;
  };
}

/**
 * Options for filtering records by type
 */
export interface ListByTypeOptions {
  spaceId?: ID | null; // undefined = Everywhere, null = Unassigned, ID = specific space
  unassignedOnly?: boolean; // true = only return items with space_id IS NULL
  subtypes?: string[]; // filter when querying notes (e.g., ['idea','list'] or ['journal'])
  tagIds?: ID[]; // filter by tags (optional - for future filtering)
  tagNames?: string[]; // normalized names (#word, *tag, @person), AND semantics
}

/**
 * Grouped items by type for Space detail view
 */
export interface GroupedByType {
  habits: AppRecord[];
  todos: AppRecord[];
  notes: AppRecord[];
}

/**
 * Repository interface - implemented by both memory and Supabase repos
 * Phase 10.9 (Today v3): extend helpers for merged today view, focus card, progress, sweep.
 */
export interface IRepo {
  // CRUD operations
  create(input: CreateRecordInput): Promise<AppRecord>;
  update(input: UpdateRecordInput): Promise<AppRecord>;
  remove(id: ID): Promise<void>;

  findNoteBySourceMessageId(sourceMessageId: string): Promise<Note | null>;
  findTodoByDropId(dropId: string): Promise<Todo | null>;
  findHabitByDropId(dropId: string): Promise<import('../types').Habit | null>;

  // Query operations
  getById(id: ID): Promise<AppRecord | null>;
  getAll(): Promise<AppRecord[]>;
  listByType(type: AppRecord['type'], opts?: ListByTypeOptions): Promise<AppRecord[]>;
  listBySpace(spaceId: ID, opts?: { tagNames?: string[] }): Promise<AppRecord[]>;
  search(text: string): Promise<AppRecord[]>;
  /**
   * Search across items within a specific space and include space chats.
   * Returns matching items (todos/notes/habits) and chats.
   */
  searchInSpace(
    spaceId: ID,
    text: string,
  ): Promise<{ items: AppRecord[]; chats: import('../types').SpaceChat[] }>;

  // Hub helpers
  countUnsorted(): Promise<number>; // counts ai_placed = true across all types

  // Today screen helpers (v2)
  listDueToday(nowIso: string): Promise<AppRecord[]>;
  listUndefinedDue(): Promise<Todo[]>;
  countPlannedToday(): Promise<number>;
  countCompletedToday(): Promise<number>;

  // =======================================================
  // Phase 10.9 (Today v3) — New helpers
  // =======================================================

  /**
   * Returns merged list of items relevant for "today":
   * - Todos due today or marked carry_forward=true and status='active'
   * - Habits where progress_today < target_count (computed from habit_progress)
   * Basic enrichment: space, tags (if cheap), and simple nearDue/overdue.
   */
  listTodayMerged(nowIso: string): Promise<
    Array<
      | {
          type: 'todo';
          id: ID;
          name: string;
          due_date?: string | null;
          due_day?: string | null;
          space_id?: ID | null;
          tags?: string[];
          status?: 'active' | 'completed' | 'archived';
          carry_forward?: boolean;
          overdue?: boolean;
          nearDue?: boolean;
        }
      | {
          type: 'habit';
          id: ID;
          name: string;
          space_id?: ID | null;
          tags?: string[];
          cadence?: 'day' | 'week' | 'month';
          target_count?: number;
          period_unit?: 'day' | 'week' | 'month';
          time_window?: 'any' | 'morning' | 'midday' | 'evening';
          progress_today?: number;
        }
    >
  >;

  /** Log a habit check-in. Count defaults to 1. */
  logHabitProgress(
    habitId: ID,
    atIso?: string,
    count?: number,
    occurrenceIndex?: number,
  ): Promise<void>;

  /** Returns total progress for a habit on a given day (UTC date string 'YYYY-MM-DD'). */
  getHabitProgressForDate(habitId: ID, dayIso: string): Promise<number>;

  /** Returns total progress for a habit within a date range (inclusive). */
  getHabitProgressForWeek(habitId: ID, weekStartIso: string, weekEndIso: string): Promise<number>;

  /** Returns the actual progress records (dates) for a habit within a date range. */
  getHabitProgressDates(habitId: ID, weekStartIso: string, weekEndIso: string): Promise<string[]>;

  /** Focus card getters/setters (one focus per owner per day). */
  getFocusForDate(dayIso: string): Promise<{
    id: ID;
    entry_id: ID | null;
    entry_type: 'todo' | 'habit' | 'note' | null;
    source: 'auto' | 'user' | 'carry_forward';
    created_at: string;
    expires_at: string;
  } | null>;

  setFocus(params: {
    entry_id: ID | null;
    entry_type: 'todo' | 'habit' | 'note' | null;
    source: 'auto' | 'user' | 'carry_forward';
    expires_at: string; // end-of-day timestamp
  }): Promise<void>;

  clearFocusForDate(dayIso: string): Promise<void>;

  /** Crude "top candidates" for focus auto-suggest. */
  topFocusCandidates(
    limit: number,
  ): Promise<Array<{ id: ID; type: 'habit' | 'todo'; priority: number }>>;

  /** Recent notes/drops since ISO timestamp — used by Drop Zone summary. */
  listRecentDrops(
    sinceIso: string,
  ): Promise<Array<{ id: ID; title?: string | null; body?: string | null; created_at: string }>>;

  /** Returns today's completed vs remaining summary for Sweep. */
  getTodaySummary(): Promise<{ completed: number; remaining: number }>;

  /** Apply Sweep action for an item. */
  sweepApplyAction(
    id: ID,
    type: 'habit' | 'todo',
    action: 'archive' | 'carry_forward' | 'keep',
    details?: { archived_reason?: string },
  ): Promise<void>;

  /** Archive all items (todos, habits, notes) with the given drop_id */
  archiveItemsByDropId(
    dropId: string,
    archivedReason?: string,
  ): Promise<{ notesArchived: number; todosArchived: number; habitsArchived: number }>;

  /** Commitments */
  listCommitments(): Promise<
    Array<{
      id: ID;
      type: 'habit' | 'todo';
      name: string;
      commitment_started_at?: string | null;
      commitment_note?: string | null;
    }>
  >;
  addCommitment(id: ID, type: 'habit' | 'todo', note?: string | null): Promise<void>;
  removeCommitment(id: ID, type: 'habit' | 'todo', reason?: string | null): Promise<void>;
  countActiveCommitments(): Promise<number>;

  // Completion methods (Phase 9)
  completeHabit(id: ID, atIso: string): Promise<void>;
  completeTodo(id: ID, atIso: string): Promise<void>;
  undoCompletion(id: ID): Promise<void>;

  // Date-specific habit completion (for weekly habit tracking)
  completeHabitForDate(habitId: ID, dateIso: string): Promise<void>;
  removeHabitCompletion(habitId: ID, dateIso: string): Promise<void>;

  /**
   * Convenience helper to add an item marked as unsorted (catch-all inbox).
   * Forces ai_placed=true and origin='catchall'. spaceId may be null for unassigned.
   */
  addUnsorted(spaceId: ID | null, input: CreateRecordInput): Promise<AppRecord>;

  /**
   * Phase 1: Create unsorted Mind Drop note before AI classification.
   * Always creates a note with:
   * - subtype: 'catchall'
   * - labels: ['catchall', 'needs_review']
   * - origin: 'catchall'
   * - ai_placed: true
   * - views.ai_pending: true (will be set to false after AI completes)
   *
   * This ensures Mind Drop always creates a single note first, then AI decides what to do with it.
   */
  createUnsortedDrop(
    text: string,
    opts?: {
      spaceId?: ID | null;
      dropId?: string | null;
      sourceMessageId?: string | null;
    },
  ): Promise<Note>;

  // Space methods (Phase 5)
  listSpaces(): Promise<Space[]>;
  createSpace(input: SpaceInsert): Promise<Space>;
  getSpaceById(spaceId: string): Promise<Space | null>;
  updateSpace(spaceId: string, patch: Partial<SpaceInsert>): Promise<Space>;
  deleteSpace(spaceId: string): Promise<void>;
  listBySpaceGrouped(spaceId: string, opts?: { tagNames?: string[] }): Promise<GroupedByType>;

  // Spaces v2 methods (Phase 8+)
  getSpaceSummary(spaceId: string): Promise<string | null>;

  // Phase 10.8: Space Insight methods
  getLatestSpaceInsight(spaceId: string): Promise<{
    summary: string;
    summary_at: string;
    tokens: number;
  } | null>;
  getSpaceInsightHistory(spaceId: string, limit?: number): Promise<any[]>;

  // Tag and People methods (Phase 7+)
  listTags(): Promise<Tag[]>;
  listPeople(): Promise<Person[]>;
  createPerson(input: {
    display_name: string;
    email?: string | null;
    dates?: Array<{ date: string; label: string }> | null;
    notes?: string | null;
    notes_fmt?: 'bullets' | 'numbers' | 'checkboxes' | null;
    reminders?: any[] | null;
    space_id?: string | null;
    tags?: string[] | null;
  }): Promise<Person>;
  updatePerson(
    personId: string,
    patch: Partial<{
      display_name: string;
      email: string | null;
      dates: Array<{ date: string; label: string }> | null;
      notes: string | null;
      notes_fmt: 'bullets' | 'numbers' | 'checkboxes' | null;
      reminders: any[] | null;
      space_id: string | null;
      tags: string[] | null;
    }>,
  ): Promise<Person>;
  deletePerson(personId: string): Promise<void>;
  listLinkedTags(entity: { type: EntityType; id: ID }): Promise<Tag[]>;
  listLinkedPeople(entity: { type: EntityType; id: ID }): Promise<Person[]>;

  // Phase 8 - Tags and People linking
  upsertTag(name: string): Promise<import('./types').Tag>;
  listItemTags(itemId: string): Promise<import('./types').Tag[]>;
  linkTag(params: {
    itemId: string;
    tagId: string;
    itemType: import('./types').ItemType;
  }): Promise<import('./types').TagMap>;
  unlinkTag(params: { itemId: string; tagId: string }): Promise<void>;
  listLinkedPeopleByItem(itemId: string): Promise<import('./types').EntityPerson[]>;
  linkPerson(params: {
    itemId: string;
    itemType: import('./types').ItemType;
    personName: string;
    personEmail?: string;
  }): Promise<import('./types').EntityPerson>;
  unlinkPerson(entityPersonId: string): Promise<void>;

  // Buddy methods (Phase 5+ stubs)
  inviteBuddy(_habitId: ID, _email: string): Promise<void>;
  acceptBuddy(_inviteToken: string): Promise<void>;
  nudgeBuddy(_habitId: ID): Promise<void>;
  unlinkBuddy(_habitId: ID): Promise<void>;

  // Phase 10.2 - Cortex Primitives

  /**
   * Get cortex preferences for a user.
   * Returns null if no preferences have been set yet.
   */
  getCortexPrefs(userId: string): Promise<import('./types').CortexPreferences | null>;

  /**
   * Set/update cortex preferences for a user (upsert).
   * Merges partial updates with existing preferences.
   */
  setCortexPrefs(
    userId: string,
    partial: import('./types').CortexPreferencesUpdate,
  ): Promise<import('./types').CortexPreferences>;

  /**
   * Get or create a list by key.
   * If the list doesn't exist, creates it with the provided or generated name.
   * Uses indexed lookup on (owner_id, key) for performance.
   */
  getOrCreateList(
    key: string,
    opts?: { userId?: string; spaceId?: string | null; name?: string },
  ): Promise<import('./types').List>;

  /**
   * Find an existing list by key (does not create).
   * Returns null if not found.
   * Uses indexed lookup on (owner_id, key).
   */
  findListByKey(
    key: string,
    opts?: { userId?: string; spaceId?: string | null },
  ): Promise<import('./types').List | null>;

  /**
   * Add an item to a list.
   * Returns the created list item with generated id.
   */
  addListItem(
    listId: string,
    label: string,
    meta?: { qty?: number; unit?: string; meta_json?: any },
  ): Promise<import('./types').ListItem>;

  /**
   * List all items in a list, ordered by created_at.
   * Uses indexed lookup on (list_id, created_at).
   */
  listItems(listId: string): Promise<import('./types').ListItem[]>;

  /**
   * Mark a list item complete/incomplete by setting/unsetting completed_at
   */
  toggleListItemComplete(listItemId: string, done: boolean): Promise<void>;

  /**
   * Rename an item (quick edit in UI)
   */
  renameListItem(listItemId: string, label: string): Promise<void>;

  /**
   * Write an event to the log (non-blocking usage expected).
   * Used for cortex decisions, user overrides, etc.
   * Uses indexed lookup on (owner_id, kind, created_at desc) for queries.
   */
  writeEvent(kind: string, payload: Record<string, any>, opts?: { userId?: string }): Promise<void>;

  // Phase 10.4 - Space defaults for Cortex biasing

  /**
   * Get defaults_json for a space.
   * Lightweight JSON config for Cortex biasing + UX hints. Treat as opaque blob.
   * Returns null if space not found or defaults_json is null.
   */
  getSpaceDefaults(spaceId: string): Promise<any | null>;

  /**
   * Set/update defaults_json for a space (shallow merge).
   * Lightweight JSON config for Cortex biasing + UX hints. Treat as opaque blob.
   * Merges patch with existing defaults at one level (no deep merge).
   * Returns updated defaults_json.
   */
  setSpaceDefaults(spaceId: string, patch: Record<string, any>): Promise<any>;

  // Phase v3.3 - Notes/Journal methods
  /**
   * List notes for a space (notes + journals).
   * Supports optional text search query.
   */
  listNotes(spaceId: string, opts?: { query?: string }): Promise<any[]>;

  /**
   * Create a note or journal entry.
   */
  createNote(input: {
    space_id: string;
    user_id: string;
    type: 'note' | 'journal';
    content: string;
    date?: string | null;
    title?: string;
  }): Promise<any>;

  /**
   * Update a note or journal entry.
   */
  updateNote(
    id: string,
    patch: Partial<{ content: string; title: string; date: string | null }>,
  ): Promise<void>;

  /**
   * Delete a note or journal entry.
   */
  deleteNote(id: string): Promise<void>;

  /**
   * Subscribe to realtime notes updates for a space.
   */
  subscribeToNotes?(spaceId: string, callback: (payload: any) => void): any;

  // Phase 10.10 - Log Photos (multi-photo journal logs)
  /**
   * List all photos for a log/note, ordered by position.
   */
  listLogPhotos(noteId: string): Promise<Array<{ id: string; url: string; position: number }>>;

  /**
   * Insert a new log photo record.
   */
  insertLogPhoto(params: {
    noteId: string;
    url: string;
    position: number;
  }): Promise<{ id: string }>;

  /**
   * Update photo position (for reordering).
   */
  updateLogPhotoPosition(photoId: string, position: number): Promise<void>;

  /**
   * Delete a log photo record.
   */
  deleteLogPhoto(photoId: string): Promise<void>;
}
