import type {
  AppRecord,
  Todo,
  ID,
  Frequency,
  NoteSubtype,
  HabitSubtype,
  Space,
  Tag,
  Person,
  EntityType,
} from '../types';
import type { SpaceInsert } from '../schemas';

/**
 * Input for creating a new record.
 * Note: owner_id, id, created_at, updated_at are auto-generated by the database.
 */
export interface CreateRecordInput {
  type: AppRecord['type'];
  name?: string; // For habits (Phase 7+) and todos (Phase 7+)
  title?: string; // For todos and notes
  body?: string;
  subtype?: NoteSubtype | HabitSubtype | 'reminder' | 'microproject' | null; // required for notes, optional for habits, AI-only for todos
  frequency?: Frequency; // required when type === 'habit'
  space_id?: ID | null;
  due_date?: string | null;
  undefined_due?: boolean; // for todos
  ai_placed?: boolean;
  why_string?: string | null;
  origin?: 'catchall';
  canonicalType?: 'note' | 'todo' | 'habit' | 'journal';
  labels?: string[];
  views?: {
    alsoShowIn?: string[];
  };
  // owner_id is optional - Supabase will set from auth context, Memory repo will use constructor userId
  owner_id?: ID;

  // Extended habit fields (Phase 7+)
  frequency_value?: any; // FrequencyValue JSON
  reminders?: any[]; // ReminderRow[] JSON
  notes?: string | null;
  tags?: string[] | null;
  buddy_id?: ID | null;
  buddy_email?: string | null;
  stack_with_id?: ID | null;
  stack_position?: 'before' | 'after' | null;
  stack_offset_minutes?: number | null;
  start_date?: string | null; // ISO date
  end_date?: string | null; // ISO date
  taper_plan?: any | null; // TaperPlanState JSON
  triggers?: string[] | null;
  replacement_habit_id?: ID | null;
  replacement_text?: string | null;

  // Extended todo fields (Phase 7+)
  due_time?: string | null; // HH:mm format for time due

  // Extended journal/note fields (Phase 7+) - only used when subtype='journal'
  date?: string | null; // ISO date for journal entry
  mood?: 'ecstatic' | 'happy' | 'neutral' | 'low' | 'sad' | 'tired' | null;
  fmt?: 'bullets' | 'numbers' | 'checkboxes' | null; // Formatting style
  journal_subtype?: 'reflection' | 'gratitude' | 'dream' | 'review' | null; // AI-only
}

/**
 * Input for updating an existing record
 */
export interface UpdateRecordInput {
  id: ID;
  patch: Partial<Omit<AppRecord, 'id' | 'type' | 'created_at' | 'owner_id'>>;
}

/**
 * Options for filtering records by type
 */
export interface ListByTypeOptions {
  spaceId?: ID | null; // undefined = Everywhere, null = Unassigned, ID = specific space
  unassignedOnly?: boolean; // true = only return items with space_id IS NULL
  subtypes?: string[]; // filter when querying notes (e.g., ['idea','list'] or ['journal'])
  tagIds?: ID[]; // filter by tags (optional - for future filtering)
}

/**
 * Grouped items by type for Space detail view
 */
export interface GroupedByType {
  habits: AppRecord[];
  todos: AppRecord[];
  notes: AppRecord[];
}

/**
 * Repository interface - implemented by both memory and Supabase repos
 */
export interface IRepo {
  // CRUD operations
  create(input: CreateRecordInput): Promise<AppRecord>;
  update(input: UpdateRecordInput): Promise<AppRecord>;
  remove(id: ID): Promise<void>;

  // Query operations
  getById(id: ID): Promise<AppRecord | null>;
  listByType(type: AppRecord['type'], opts?: ListByTypeOptions): Promise<AppRecord[]>;
  listBySpace(spaceId: ID): Promise<AppRecord[]>;
  search(text: string): Promise<AppRecord[]>;

  // Hub helpers
  countUnsorted(): Promise<number>; // counts ai_placed = true across all types

  // Today screen helpers
  listDueToday(nowIso: string): Promise<AppRecord[]>;
  listUndefinedDue(): Promise<Todo[]>;

  // Space methods (Phase 5)
  listSpaces(): Promise<Space[]>;
  createSpace(input: SpaceInsert): Promise<Space>;
  getSpaceById(spaceId: string): Promise<Space | null>;
  updateSpace(spaceId: string, patch: Partial<SpaceInsert>): Promise<Space>;
  deleteSpace(spaceId: string): Promise<void>;
  listBySpaceGrouped(spaceId: string): Promise<GroupedByType>;

  // Tag and People methods (Phase 7+)
  listTags(): Promise<Tag[]>;
  listPeople(): Promise<Person[]>;
  createPerson(input: {
    display_name: string;
    email?: string | null;
    dates?: Array<{ date: string; label: string }> | null;
    notes?: string | null;
    notes_fmt?: 'bullets' | 'numbers' | 'checkboxes' | null;
    reminders?: any[] | null;
    space_id?: string | null;
    tags?: string[] | null;
  }): Promise<Person>;
  updatePerson(
    personId: string,
    patch: Partial<{
      display_name: string;
      email: string | null;
      dates: Array<{ date: string; label: string }> | null;
      notes: string | null;
      notes_fmt: 'bullets' | 'numbers' | 'checkboxes' | null;
      reminders: any[] | null;
      space_id: string | null;
      tags: string[] | null;
    }>,
  ): Promise<Person>;
  deletePerson(personId: string): Promise<void>;
  listLinkedTags(entity: { type: EntityType; id: ID }): Promise<Tag[]>;
  listLinkedPeople(entity: { type: EntityType; id: ID }): Promise<Person[]>;

  // Buddy methods (Phase 5+ stubs)
  inviteBuddy(_habitId: ID, _email: string): Promise<void>;
  acceptBuddy(_inviteToken: string): Promise<void>;
  nudgeBuddy(_habitId: ID): Promise<void>;
  unlinkBuddy(_habitId: ID): Promise<void>;
}
