import type { AppRecord, Todo, ID, Frequency, NoteSubtype, Space } from '../types';
import type { SpaceInsert } from '../schemas';

/**
 * Input for creating a new record.
 * Note: owner_id, id, created_at, updated_at are auto-generated by the database.
 */
export interface CreateRecordInput {
  type: AppRecord['type'];
  title: string;
  body?: string;
  subtype?: NoteSubtype; // required when type === 'note'
  frequency?: Frequency; // required when type === 'habit'
  space_id?: ID | null;
  due_date?: string | null;
  undefined_due?: boolean; // for todos
  ai_placed?: boolean;
  why_string?: string | null;
  // owner_id is optional - Supabase will set from auth context, Memory repo will use constructor userId
  owner_id?: ID;
}

/**
 * Input for updating an existing record
 */
export interface UpdateRecordInput {
  id: ID;
  patch: Partial<Omit<AppRecord, 'id' | 'type' | 'created_at' | 'owner_id'>>;
}

/**
 * Grouped items by type for Space detail view
 */
export interface GroupedByType {
  habits: AppRecord[];
  todos: AppRecord[];
  notes: AppRecord[];
}

/**
 * Repository interface - implemented by both memory and Supabase repos
 */
export interface IRepo {
  // CRUD operations
  create(input: CreateRecordInput): Promise<AppRecord>;
  update(input: UpdateRecordInput): Promise<AppRecord>;
  remove(id: ID): Promise<void>;

  // Query operations
  getById(id: ID): Promise<AppRecord | null>;
  listByType(type: AppRecord['type']): Promise<AppRecord[]>;
  listBySpace(spaceId: ID): Promise<AppRecord[]>;
  search(text: string): Promise<AppRecord[]>;

  // Today screen helpers
  listDueToday(nowIso: string): Promise<AppRecord[]>;
  listUndefinedDue(): Promise<Todo[]>;

  // Space methods (Phase 5)
  listSpaces(): Promise<Space[]>;
  createSpace(input: SpaceInsert): Promise<Space>;
  getSpaceById(spaceId: string): Promise<Space | null>;
  updateSpace(spaceId: string, patch: Partial<SpaceInsert>): Promise<Space>;
  deleteSpace(spaceId: string): Promise<void>;
  listBySpaceGrouped(spaceId: string): Promise<GroupedByType>;

  // Buddy methods (Phase 5+ stubs)
  inviteBuddy(_habitId: ID, _email: string): Promise<void>;
  acceptBuddy(_inviteToken: string): Promise<void>;
  nudgeBuddy(_habitId: ID): Promise<void>;
  unlinkBuddy(_habitId: ID): Promise<void>;
}
